import { useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { Container, Heading, Button, Text, Textarea } from '@chakra-ui/react'
import { useHotkeys } from 'react-hotkeys-hook'


export default function Home() {
  const [ mbtiFirst, setMbtiFirst ] = useState('I')
  const [ mbtiSecond, setMbtiSecond ] = useState('S')
  const [ mbtiThird, setMbtiThird ] = useState('T')
  const [ mbtiFourth, setMbtiFourth ] = useState('J')
  const [ feeling, setFeeling ] = useState('')

  useHotkeys('e', () => setMbtiFirst('E'), [mbtiFirst])
  useHotkeys('i', () => setMbtiFirst('I'), [mbtiFirst])
  useHotkeys('n', () => setMbtiSecond('N'), [mbtiSecond])
  useHotkeys('s', () => setMbtiSecond('S'), [mbtiSecond])
  useHotkeys('f', () => setMbtiThird('F'), [mbtiThird])
  useHotkeys('t', () => setMbtiThird('T'), [mbtiThird])
  useHotkeys('p', () => setMbtiFourth('P'), [mbtiFourth])
  useHotkeys('j', () => setMbtiFourth('J'), [mbtiFourth])

  useEffect(() => {})
  return (
    <>
      <Head>
        <title>인공지능 조향기를 이용한 나만의 향수 만들기</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.xl" textAlign='center' paddingTop='12'>
        <Heading as='h2' size='lg' fontWeight='normal'>TESLA</Heading>
        <Heading as='h1' size='2xl' fontWeight='semibold'>인공지능 조향기를 이용한 나만의 향수 만들기</Heading>
      </Container>
      <Container mt={20} textAlign='center'>
        <Heading size='md' mb={4}>MBTI: {mbtiFirst}{mbtiSecond}{mbtiThird}{mbtiFourth}</Heading>
        <Button colorScheme='blue' mr={2} onClick={() => setMbtiFirst('I')} variant={mbtiFirst === 'I' ? 'solid' : 'outline'}>I</Button>
        <Button colorScheme='blue' mr={8} onClick={() => setMbtiFirst('E')} variant={mbtiFirst === 'E' ? 'solid' : 'outline'}>E</Button>

        <Button colorScheme='yellow' mr={2} onClick={() => setMbtiSecond('S')} variant={mbtiSecond === 'S' ? 'solid' : 'outline'}>S</Button>
        <Button colorScheme='yellow' mr={8} onClick={() => setMbtiSecond('N')} variant={mbtiSecond === 'N' ? 'solid' : 'outline'}>N</Button>

        <Button colorScheme='green' mr={2} onClick={() => setMbtiThird('T')} variant={mbtiThird === 'T' ? 'solid' : 'outline'}>T</Button>
        <Button colorScheme='green' mr={8} onClick={() => setMbtiThird('F')} variant={mbtiThird === 'F' ? 'solid' : 'outline'}>F</Button>

        <Button colorScheme='red' mr={2} onClick={() => setMbtiFourth('J')} variant={mbtiFourth === 'J' ? 'solid' : 'outline'}>J</Button>
        <Button colorScheme='red' mr={8} onClick={() => setMbtiFourth('P')} variant={mbtiFourth === 'P' ? 'solid' : 'outline'}>P</Button>
      
        <Heading size='md' mt={12} mb={4}>오늘의 기분 또는 지금 드는 생각(고민/기분 등등):</Heading>
        <Textarea borderColor='gray.300' placeholder='친구와 싸웠는데 화해를 어떻게 할지 모르겠어요.' onChange={(e) => setFeeling(e.target.value)}>{feeling}</Textarea>
          <Button as={Link} href={`/create?mbti=${mbtiFirst}${mbtiSecond}${mbtiThird}${mbtiFourth}&feeling=${feeling}&nonce=${Math.random().toString(16).substring(2, 11)}`} isDisabled={!feeling} colorScheme='blue' mt={4}>향수 제작하기</Button>
      </Container>

    </>
  )
}
