import { Container, Heading } from '@chakra-ui/react'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.xl" textAlign='center' paddingTop='12'>
        <Heading as='h2' size='lg'>TESLA</Heading>
        <Heading as='h1' size='3xl'>나만의 향수 만들기 체험 부스</Heading>
      </Container>
    </>
  )
}
